<a href="https://colab.research.google.com/github/Hanna025/Oyesters_Assignments/blob/master/Assignment_Day2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Create an array having 10 values using randint method and store it in a variable r. Values ranging from 50 to 100. Sort it in descending order

In [7]:
import numpy as np

r = np.random.randint(50,100,10)
print(np.sort(r))
desc = np.sort(r)[::-1]
print(desc)


[55 59 61 65 70 73 76 82 87 96]
[96 87 82 76 73 70 65 61 59 55]


2. Append a number 7 inside r array

In [9]:
np.append(np.sort(r),7)

array([55, 59, 61, 65, 70, 73, 76, 82, 87, 96,  7])

3. Find the cubes and square roots of all values of r array and store in c and sq variable.


In [10]:
c = np.power(r,3)
print(c)
sq = np.power(r,2)
print(sq)

[438976 166375 389017 274625 226981 343000 658503 551368 205379 884736]
[5776 3025 5329 4225 3721 4900 7569 6724 3481 9216]


4. Print the following of r array
The total sum;
Maximum value;
Minimum Value;
Mean Value;
Median Value;


In [11]:
print(np.sum(r))
print(np.max(r))
print(np.min(r))
print(np.mean(r))
print(np.median(r))

724
96
55
72.4
71.5


5.Normalize the r array and store it in varible n using Min Max
Hint : Minmax normalization is a normalization strategy which linearly transforms minimum value in array is mapped to 0 and the maximum value in array is mapped to 1. Check Image for formula reference

In [14]:
r = np.random.randint(50,100,10)
n = (r - min(r))/(max(r) - min(r))
print(normalised)

[0.51219512 0.         0.43902439 0.24390244 0.14634146 0.36585366
 0.7804878  0.65853659 0.09756098 1.        ]
